# Generated by Django 3.2.5 on 2022-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingTrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Username')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount Spent')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('note', models.CharField(max_length=200, verbose_name='Transaction Note')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
            ],
        ),
    ]
