# Generated by Django 3.2.5 on 2022-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0002_auto_20220304_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingtrs',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
